server {
    listen 80;
    server_name urlx.jhoja.tech;
    
    # HTTP to HTTPS 
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name urlx.jhoja.tech;

    # SSL Certificates 
    ssl_certificate /etc/letsencrypt/live/urlx.jhoja.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/urlx.jhoja.tech/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}